### ISSUE TITLE
Expose visibility of holographic target location

### ISSUE THREAD

**Issue by CodyCBakerPhD** [catalystneuro/pinto-lab-to-nwb#28]
Oh yes, no you're right it should have more visibility. Can I add it in a follow up? It's getting hard to separate this from #5 when running a full conversion 😅

_Originally posted by @weiglszonja in https://github.com/catalystneuro/pinto-lab-to-nwb/pull/23#discussion_r1419495291_

**Comment by weiglszonja** [comment]
Completed in #30
